package history

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

const recordSep byte = 0x1e

// ParseLog streams the strict NUL-delimited output generated by LogArgs. A
// commit header is RS + unix timestamp + NUL. Git places one structural LF
// before the first path for that commit; only that framing byte is removed.
// Filename bytes are otherwise never trimmed or normalized.
func ParseLog(r io.Reader, repo RepoKind) (map[string]time.Time, error) {
	br := bufio.NewReader(r)
	out := map[string]time.Time{}
	var current time.Time
	haveCommit := false
	needFirstPath := false
	combinedNames := false
	for {
		tok, done, err := readNULTerminated(br)
		if err != nil {
			return nil, err
		}
		if done {
			break
		}
		if len(tok) == 0 {
			// Combined merge output inserts an empty NUL token before its name
			// list. A following path has no structural LF; a following header (or
			// EOF) means the merge had no relevant paths.
			if needFirstPath {
				needFirstPath = false
				combinedNames = true
				continue
			}
			return nil, fmt.Errorf("empty token in git log")
		}
		if tok[0] == recordSep {
			if needFirstPath {
				return nil, fmt.Errorf("commit header without a path")
			}
			if bytes.Contains(tok[1:], []byte{recordSep}) {
				return nil, fmt.Errorf("malformed commit framing")
			}
			raw := string(tok[1:])
			if raw == "" {
				return nil, fmt.Errorf("invalid commit timestamp %q", raw)
			}
			for _, b := range []byte(raw) {
				if b < '0' || b > '9' {
					return nil, fmt.Errorf("invalid commit timestamp %q", raw)
				}
			}
			sec, parseErr := strconv.ParseInt(raw, 10, 64)
			if parseErr != nil {
				return nil, fmt.Errorf("invalid commit timestamp %q", raw)
			}
			current = time.Unix(sec, 0).UTC()
			haveCommit = true
			needFirstPath = true
			combinedNames = false
			continue
		}
		if !haveCommit {
			return nil, fmt.Errorf("path before commit header")
		}
		if combinedNames {
			if tok[0] == '\n' {
				return nil, fmt.Errorf("combined path has regular framing newline")
			}
			combinedNames = false
		} else if needFirstPath {
			if tok[0] != '\n' {
				return nil, fmt.Errorf("missing path framing newline")
			}
			tok = tok[1:]
			needFirstPath = false
			if len(tok) == 0 {
				return nil, fmt.Errorf("empty path in git log")
			}
		}
		if bytes.Contains(tok, []byte{recordSep}) {
			return nil, fmt.Errorf("record separator in path")
		}
		if id, ok := IdentifierFromPath(repo, string(tok)); ok {
			if old, exists := out[id]; !exists || current.Before(old) {
				out[id] = current
			}
		}
	}
	if !haveCommit {
		return out, nil
	}
	if needFirstPath {
		return nil, fmt.Errorf("commit header without a path")
	}
	return out, nil
}

func readNULTerminated(br *bufio.Reader) ([]byte, bool, error) {
	tok, err := br.ReadBytes(0)
	if err == io.EOF {
		if len(tok) != 0 {
			return nil, false, fmt.Errorf("truncated non-NUL git log token")
		}
		return nil, true, nil
	}
	if err != nil {
		return nil, false, err
	}
	return tok[:len(tok)-1], false, nil
}
